Retire Hibernate OGM from the front page and menus
hibernate/hibernate.org pull request #162
Opened 2022-03-07 10:23 UTC by gsmet

@DavideD @yrodiere I think it's time to do that.

The menu is still active when you go to the OGM section from the Others page (or if you get to the `/ogm/` page from Google).
I also moved Hibernate Reactive before Tools consistently as I think it makes more sense from a user perspective.

2022-03-07 10:30 UTC, yrodiere commented
Pushed to staging, should show up soon: https://staging.hibernate.org/

2022-03-07 10:42 UTC, yrodiere requested changes
I agree on the principle, but I think there are a few missing things.

I think you forgot to update the `/community/` pages? Or is that on purpose? I'm not sure we should keeep OGM there...

Regardless, Reactive is listed after Tools on the `/community` pages, so if you want to be consistent, that at least should be addressed.

By the way, I just noticed we don't have a list a contributors for Hibernate Reactive (no `/community/contributors/reactive.html.haml`, no corresponding entry in the community left menu)...

Also, we should remember to update menus on in.relation.to! And probably update the OGM category on Discourse as well.

2022-03-07 10:42 UTC, yrodiere commented on others/index.adoc
> +and is not maintained anymore by the Hibernate team.
This sentence feels weird. Maybe rather:

```suggestion
and is not maintained by the Hibernate team anymore.
```

Or if you're worried about confusions:

```suggestion
and is not maintained anymore.
```

2022-03-07 10:42 UTC, yrodiere commented on others/index.adoc
> +Hibernate OGM has not been kept up to date with the latest Hibernate ORM versions
Shouldn't we add a banner with a similar message to all OGM pages? Otherwise, people coming from external websites won't know about it...

2022-03-07 11:41 UTC, gsmet commented
@yrodiere I have addressed all your concerns.

2022-03-08 08:37 UTC, yrodiere approved these changes
Thanks. I added a few commits to add a warning sign on deprecation notices, to avoid dead links and to display a deprecation notice on community/contributors.

Looks good to merge as far as I'm concerned. @DavideD , any opinion?

2022-03-08 15:32 UTC, DavideD approved these changes
Thanks!

2022-03-08 15:34 UTC, DavideD commented
Rebased and merged

2022-03-08 15:34 UTC, closed without merging